name: Test the website build
on:
  pull_request:
    types:
      - ready_for_review
      - review_requested
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install and build the site
        run: |
          npm install
          npm run build

      - name: Deploy the site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: site
          publish_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the test branch
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Test deploying the site to Dreamhost
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.HOST }}
          destination-path: ${{ secrets.DESTINATION }}
          remote-user: ${{ secrets.USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./
          rsync-options: --dry-run
