name: Test the website build
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the working branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install and build the site
        run: |
          npm install
          npm run build

      - name: Deploy the site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: site
          publish_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
